### ISSUE TITLE
[BUG]: V11 Incompatibility

### ISSUE THREAD

**Issue by Orionox** [ZotyDev/objects-interactions-fx#24]
### Discord Username

Orionox

### Browsers

Native Foundry Client

### What Happened?

the module is preventing scenes from being loaded

### Reproduction Steps

```bash
1. Activate module
2. Load scene
3. screen is blank
```

### Relevant Log Output

```Shell
foundry.js:753 TypeError: Error thrown in hooked function '' for hook 'updateScene'. Cannot read properties of null (reading 'flags')
[Detected 1 package: wall-height]
    at getSceneSettings (utils.js:37:32)
    at set currentTokenElevation [as currentTokenElevation] (patches.js:29:32)
    at WallHeightUtils.updateCurrentTokenElevation (patches.js:66:34)
    at Object.fn (patches.js:369:16)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at ClientDatabaseBackend.callback (foundry.js:13669:13)
    at foundry.js:13642:43
    at Array.map (<anonymous>)
    at #handleUpdateDocuments (foundry.js:13642:33)
```

**Comment by ZotyDev** [comment]
Currently there is a bug that prevents V11 scenes from loading, this will be fixed on the next release.

**Comment by Kiiinji** [comment]
Any update for this issue?

**Comment by ZotyDev** [comment]
Sorry for the delay, OIF just got updated to V11 and should be working smoothly now.
V2.0.0 still WIP
