### ISSUE TITLE
Currency not being generated

### ISSUE THREAD

**Issue by ravingdragoon** [ZotyDev/objects-interactions-fx#5]
Currently I am not able to generate currency.  I am receiving the error below with only this module and its required and optional modules (minus Fluid Canvas) and Find the Culprit enabled. I am running DnD5e 2.1.4 and Foundry v10 Build 291.

```
Uncaught (in promise) TypeError: undefined. Tags.indexOf is not a function
[Detected 1 package: objects-interactions-fx]
    at Object.fn (ActorInventor.js:12:22)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at ClientDatabaseBackend.callback (foundry.js:12613:13)
    at foundry.js:12594:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleCreateEmbeddedDocuments (foundry.js:12594:33)
    at ClientDatabaseBackend._createEmbeddedDocuments (foundry.js:12499:17)
    at async TokenDocument5e.createDocuments (commons.js:6110:23)
    at async TokenDocument5e.create (commons.js:6233:23)
(anonymous) @ ActorInventor.js:12
#call @ foundry.js:724
callAll @ foundry.js:681
callback @ foundry.js:12613
(anonymous) @ foundry.js:12594
_handleCreateEmbeddedDocuments @ foundry.js:12594
_createEmbeddedDocuments @ foundry.js:12499
await in _createEmbeddedDocuments (async)
create @ commons.js:6737
await in create (async)
createDocuments @ commons.js:6110
create @ commons.js:6233
_onDropActorData @ foundry.js:37358
await in _onDropActorData (async)
_onDrop @ foundry.js:24689
callback @ foundry.js:56837
_handleDrop @ foundry.js:56888
06:35:27.869 
```

**Comment by ZotyDev** [comment]
Hm, thats odd.
Are you generating currency for a linked token?
Also, what is your browser?

**Comment by ZotyDev** [comment]
Can you check if the error happens on a fresh world?

**Comment by ravingdragoon** [comment]
I am using Google Chrome. I am using a single dagger with the tag "dagger" (no actual quotes) which I guess would be a melee weapon transformed to thrown. The error does <i>not</i> occur with the default NPC sheet. On a fresh world it still happens, however the error message is different. A difference that I notice when using the tidy5e sheet is that the dagger does not show get automatically removed from the sheet, it still shows as an equipped item until I close the sheet (at which point I cannot open it again).

```
TypeError: An error occurred while rendering Tidy5eNPC 52. Cannot read properties of undefined (reading 'getChatData')
[Detected 4 packages: system:dnd5e, tidy5e-sheet, item-piles, lib-wrapper]
    at Tidy5eNPC.getData (base-sheet.mjs:166:64)
    at Tidy5eNPC.getData (npc-sheet.mjs:27:33)
    at Tidy5eNPC.getData (tidy5e-npc.js:193:31)
    at Tidy5eNPC._render (foundry.js:5108:29)
    at Tidy5eNPC._render (foundry.js:5822:17)
    at Tidy5eNPC.render (foundry.js:5067:10)
    at Tidy5eNPC.render (foundry.js:6394:18)
    at Token5e._onClickLeft2 (foundry.js:47378:16)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Token.prototype._onClickLeft2#item-piles (libwrapper.js:13:12)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Token.prototype._onClickLeft2#0 (libWrapper-wrapper.js:189:20)
    at MouseInteractionManager.callback (foundry.js:27813:45)
    at MouseInteractionManager._handleClickLeft2 (foundry.js:28027:17)
    at MouseInteractionManager._handleMouseDown (foundry.js:27989:66)
    at a.emit (index.js:181:35)
    at r.dispatchEvent (interaction.min.mjs:8:12235)
    at r.processPointerDown (interaction.min.mjs:8:14214)
    at t.recursiveFindHit (interaction.min.mjs:8:4098)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.findHit (interaction.min.mjs:8:4157)
    at r.processInteractive (interaction.min.mjs:8:12841)
    at r.onPointerDown (interaction.min.mjs:8:13543)
onError @ foundry.js:747
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁Hooks.onError#lib-wrapper @ listeners.js:138
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
(anonymous) @ foundry.js:5069
Promise.catch (async)
render @ foundry.js:5067
render @ foundry.js:6394
_onClickLeft2 @ foundry.js:47378
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁Token.prototype._onClickLeft2#item-piles @ libwrapper.js:13
🎁call_wrapper @ libWrapper-wrapper.js:616
🎁Token.prototype._onClickLeft2#0 @ libWrapper-wrapper.js:189
callback @ foundry.js:27813
_handleClickLeft2 @ foundry.js:28027
_handleMouseDown @ foundry.js:27989
a.emit @ index.js:181
r.dispatchEvent @ interaction.min.mjs:8
r.processPointerDown @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.findHit @ interaction.min.mjs:8
r.processInteractive @ interaction.min.mjs:8
r.onPointerDown @ interaction.min.mjs:8
```

**Comment by ravingdragoon** [comment]
This is my bad, I somehow missed the setup section for this in the wiki.
